sudo: required

services:
    - docker

before_install:
    - docker build -t mistermcodes/docker-udemy-react -f Dockerfile.dev .    

script:
    - docker run -e CI=true mistermcodes/docker-udemy-react npm run test

language: generic